ARG BASE_IMAGE=arm32v7/openjdk:11-jre-slim
FROM $BASE_IMAGE

COPY qemu-arm-static /usr/bin

VOLUME /tmp
ADD /target/spring-boot-docker-0.0.1-SNAPSHOT.jar app.jar
RUN rm /usr/bin/qemu-arm-static
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
